### ISSUE TITLE
Make allow-directory-listing and provide-index-page compatible

### ISSUE THREAD

**Issue by johanvdw** [nginxinc/nginx-s3-gateway#112]
I wonder if it is somehow possible to have directory listings in case the index.html page does not exist. I realise that in that case two requests to s3 have to be made, either first the page and then the listing if that fails, or first the listing and then the page if it is in the list.

**Comment by dekobon** [comment]
Hi @johanvdw, even if we wanted to do two requests to s3, I don't think we can do it with the current implementation of nginx and njs. If we make a s3 gateway binary module, then it may be possible.

**Comment by ajschmidt8** [comment]
@dekobon, I also have a use case where I need both `ALLOW_DIRECTORY_LIST` and `PROVIDE_INDEX_PAGE` to be enabled.

Is there any way we could make this work?

I'm happy to open a PR if we can agree on an approach.

**Comment by dekobon** [comment]
There may be a way now. Njs now supports [XML](https://nginx.org/en/docs/njs/reference.html#xml)

So, you could parse the output of the directory list results and determine if there are no results. Basically, you would rewrite the logic [here](https://github.com/nginxinc/nginx-s3-gateway/blob/master/common/etc/nginx/include/s3gateway.js#L354).

Then, one may could use [fetch](https://nginx.org/en/docs/njs/reference.html#ngx_fetch) to get the index page. When doing that, you may actually want to fetch the index page by querying the S3 gateway itself over localhost so that the aws auth creds are embedded.

**Comment by ajschmidt8** [comment]
Ok. I will try to take a look at this when time permits.

Please feel free to leave additional feedback on the approach if anything comes to mind.

In the meantime, can you re-open this issue, @dekobon?

**Comment by dekobon** [comment]
I wonder if you could modify it to a redirect of the location of the index page?

**Comment by AyodeAwe** [comment]
Hmm, seems like `r.internalRedirect` simply gets ignored when called in `js_body_filter`. I created an issue in the `njs` repo describing this.

https://github.com/nginx/njs/issues/645

**Comment by ajschmidt8** [comment]
@dekobon, it looks like @AyodeAwe has opened a PR for this https://github.com/nginxinc/nginx-s3-gateway/pull/139.

Can you take a look when you have a moment?

He uses a combination of `js_content` and `ngx.fetch` to see if an `index.html` page exists for a specific directory. If it does, he loads it. Otherwise, he loads the directory listing.

**Comment by dekobon** [comment]
Thank you @ajschmidt8 !

Resolved in PR #139
