### ISSUE TITLE
Support for index documents

### ISSUE THREAD

**Issue by keot** [nginxinc/nginx-s3-gateway#13]
Thank you for an extremely useful proxy!

At the moment the S3 signature is calculated with the original URI, therefore there's no ability to rewrite this URI to access an `index.html` or equivalent document.

My crude attempt to redirect root requests to an index document is below. It basically bypasses the proxy for any path without a file extension and sends it directly to S3. Not ideal.

```
    location ~ ^[^\.]*\/?$ {
        proxy_pass_request_headers off;
        proxy_set_header Host '${S3_BUCKET_NAME}.${S3_SERVER}';
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_intercept_errors on;
        js_header_filter s3gateway.filterOutAmzHeaders;
        rewrite ^[^\.]*\/?$ /index.html break;  # don't care
        proxy_pass ${S3_SERVER_PROTO}://${S3_SERVER};
    }
```

Any further ideas would be appreciated.

**Comment by dekobon** [comment]
It seems like you may be able to detect if the request is pointing to a directory by hooking into the njs logic [here](https://github.com/nginxinc/nginx-s3-gateway/blob/master/common/etc/nginx/include/s3gateway.js#L228) and then doing an internal redirect to a location. As for rewritting to index.html, this could be done in the [s3uri function](https://github.com/nginxinc/nginx-s3-gateway/blob/master/common/etc/nginx/include/s3gateway.js#L173). If you modify the request URI here and transform it, it can then be passed along to the rest of the authentication logic.

I'd love to see index files supported, however making it work side by side directory listings may not be possible because it would require making a request out to S3 to see if an index file exists and then displaying a listing only if an index file wasn't found.

If you get this working, I would love to see a PR or some example code that we could work into the repository.

**Comment by Gamecock** [comment]
I'm still working though auth issues, so I have not been able to test yet, but should this change to s3uri(r) work.  I'm trying to front a static Website in a VPC with private bucket endpoint.

```    if (allow_listing) {
        var queryParams = _s3DirQueryParams(uriPath, r.method);
        if (queryParams.length > 0) {
            path = basePath + '/?' + queryParams;
        } else {
            if ( uriPath.endsWith('/')) {
                uriPath +="index.html";
            }
            path = basePath + uriPath;
        }```

**Comment by Gamecock** [comment]
That won't work because the "/" is getting redirected in function redirectToS3(r)

**Comment by Gamecock** [comment]
stupid question, how do I enable debug so ` _debug_log`prints.  My second attempt at this is generating a 403.

**Comment by dekobon** [comment]
If you are running njs via nginx (not stand-alone on the cli), you can log by using the `.log()` method on the request object.
